# fly.toml app configuration file generated for session-zero-8cuvzw on 2026-09-20T15:17:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'session-zero-8cuvzw'
primary_region = 'lax'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
